from typing import overload, TYPE_CHECKING

if TYPE_CHECKING:
    import lielab

# commutator
@overload
def commutator(x: lielab.domain.cn, y: lielab.domain.cn) -> lielab.domain.cn: ...
@overload
def commutator(x: lielab.domain.glc, y: lielab.domain.glc) -> lielab.domain.glc: ...
@overload
def commutator(x: lielab.domain.glr, y: lielab.domain.glr) -> lielab.domain.glr: ...
@overload
def commutator(x: lielab.domain.rn, y: lielab.domain.rn) -> lielab.domain.rn: ...
@overload
def commutator(x: lielab.domain.se, y: lielab.domain.se) -> lielab.domain.se: ...
@overload
def commutator(x: lielab.domain.so, y: lielab.domain.so) -> lielab.domain.so: ...
@overload
def commutator(x: lielab.domain.sp, y: lielab.domain.sp) -> lielab.domain.sp: ...
@overload
def commutator(x: lielab.domain.su, y: lielab.domain.su) -> lielab.domain.su: ...
@overload
def commutator(x: lielab.domain.CompositeAlgebra, y: lielab.domain.CompositeAlgebra) -> lielab.domain.CompositeAlgebra: ...

# ad
@overload
def ad_numerical(x: lielab.domain.cn, power: int = 1) -> lielab.domain.glr: ...
@overload
def ad_numerical(x: lielab.domain.cn, y: lielab.domain.cn, power: int = 1) -> lielab.domain.cn: ...
@overload
def ad_numerical(x: lielab.domain.glc, power: int = 1) -> lielab.domain.glr: ...
@overload
def ad_numerical(x: lielab.domain.glc, y: lielab.domain.glc, power: int = 1) -> lielab.domain.glc: ...
@overload
def ad_numerical(x: lielab.domain.glr, power: int = 1) -> lielab.domain.glr: ...
@overload
def ad_numerical(x: lielab.domain.glr, y: lielab.domain.glr, power: int = 1) -> lielab.domain.glr: ...
@overload
def ad_numerical(x: lielab.domain.rn, power: int = 1) -> lielab.domain.glr: ...
@overload
def ad_numerical(x: lielab.domain.rn, y: lielab.domain.rn, power: int = 1) -> lielab.domain.rn: ...
@overload
def ad_numerical(x: lielab.domain.se, power: int = 1) -> lielab.domain.glr: ...
@overload
def ad_numerical(x: lielab.domain.se, y: lielab.domain.se, power: int = 1) -> lielab.domain.se: ...
@overload
def ad_numerical(x: lielab.domain.so, power: int = 1) -> lielab.domain.glr: ...
@overload
def ad_numerical(x: lielab.domain.so, y: lielab.domain.so, power: int = 1) -> lielab.domain.so: ...
@overload
def ad_numerical(x: lielab.domain.sp, power: int = 1) -> lielab.domain.glr: ...
@overload
def ad_numerical(x: lielab.domain.sp, y: lielab.domain.sp, power: int = 1) -> lielab.domain.sp: ...
@overload
def ad_numerical(x: lielab.domain.su, power: int = 1) -> lielab.domain.glr: ...
@overload
def ad_numerical(x: lielab.domain.su, y: lielab.domain.su, power: int = 1) -> lielab.domain.su: ...
@overload
def ad_numerical(x: lielab.domain.CompositeAlgebra, power: int = 1) -> lielab.domain.CompositeAlgebra: ...
@overload
def ad_numerical(x: lielab.domain.CompositeAlgebra, y: lielab.domain.CompositeAlgebra, power: int = 1) -> lielab.domain.CompositeAlgebra: ...

@overload
def ad(x: lielab.domain.cn, power: int = 1) -> lielab.domain.glr: ...
@overload
def ad(x: lielab.domain.cn, y: lielab.domain.cn, power: int = 1) -> lielab.domain.cn: ...
@overload
def ad(x: lielab.domain.glc, power: int = 1) -> lielab.domain.glr: ...
@overload
def ad(x: lielab.domain.glc, y: lielab.domain.glc, power: int = 1) -> lielab.domain.glc: ...
@overload
def ad(x: lielab.domain.glr, power: int = 1) -> lielab.domain.glr: ...
@overload
def ad(x: lielab.domain.glr, y: lielab.domain.glr, power: int = 1) -> lielab.domain.glr: ...
@overload
def ad(x: lielab.domain.rn, power: int = 1) -> lielab.domain.glr: ...
@overload
def ad(x: lielab.domain.rn, y: lielab.domain.rn, power: int = 1) -> lielab.domain.rn: ...
@overload
def ad(x: lielab.domain.se, power: int = 1) -> lielab.domain.glr: ...
@overload
def ad(x: lielab.domain.se, y: lielab.domain.se, power: int = 1) -> lielab.domain.se: ...
@overload
def ad(x: lielab.domain.so, power: int = 1) -> lielab.domain.glr: ...
@overload
def ad(x: lielab.domain.so, y: lielab.domain.so, power: int = 1) -> lielab.domain.so: ...
@overload
def ad(x: lielab.domain.sp, power: int = 1) -> lielab.domain.glr: ...
@overload
def ad(x: lielab.domain.sp, y: lielab.domain.sp, power: int = 1) -> lielab.domain.sp: ...
@overload
def ad(x: lielab.domain.su, power: int = 1) -> lielab.domain.glr: ...
@overload
def ad(x: lielab.domain.su, y: lielab.domain.su, power: int = 1) -> lielab.domain.su: ...
@overload
def ad(x: lielab.domain.CompositeAlgebra, power: int = 1) -> lielab.domain.CompositeAlgebra: ...
@overload
def ad(x: lielab.domain.CompositeAlgebra, y: lielab.domain.CompositeAlgebra, power: int = 1) -> lielab.domain.CompositeAlgebra: ...

# coad
@overload
def coad_numerical(x: lielab.domain.cn, power: int = 1) -> lielab.domain.glr: ...
@overload
def coad_numerical(x: lielab.domain.cn, y: lielab.domain.cn, power: int = 1) -> lielab.domain.cn: ...
@overload
def coad_numerical(x: lielab.domain.glc, power: int = 1) -> lielab.domain.glr: ...
@overload
def coad_numerical(x: lielab.domain.glc, y: lielab.domain.glc, power: int = 1) -> lielab.domain.glc: ...
@overload
def coad_numerical(x: lielab.domain.glr, power: int = 1) -> lielab.domain.glr: ...
@overload
def coad_numerical(x: lielab.domain.glr, y: lielab.domain.glr, power: int = 1) -> lielab.domain.glr: ...
@overload
def coad_numerical(x: lielab.domain.rn, power: int = 1) -> lielab.domain.glr: ...
@overload
def coad_numerical(x: lielab.domain.rn, y: lielab.domain.rn, power: int = 1) -> lielab.domain.rn: ...
@overload
def coad_numerical(x: lielab.domain.se, power: int = 1) -> lielab.domain.glr: ...
@overload
def coad_numerical(x: lielab.domain.se, y: lielab.domain.se, power: int = 1) -> lielab.domain.se: ...
@overload
def coad_numerical(x: lielab.domain.so, power: int = 1) -> lielab.domain.glr: ...
@overload
def coad_numerical(x: lielab.domain.so, y: lielab.domain.so, power: int = 1) -> lielab.domain.so: ...
@overload
def coad_numerical(x: lielab.domain.sp, power: int = 1) -> lielab.domain.glr: ...
@overload
def coad_numerical(x: lielab.domain.sp, y: lielab.domain.sp, power: int = 1) -> lielab.domain.sp: ...
@overload
def coad_numerical(x: lielab.domain.su, power: int = 1) -> lielab.domain.glr: ...
@overload
def coad_numerical(x: lielab.domain.su, y: lielab.domain.su, power: int = 1) -> lielab.domain.su: ...
@overload
def coad_numerical(x: lielab.domain.CompositeAlgebra, power: int = 1) -> lielab.domain.CompositeAlgebra: ...
@overload
def coad_numerical(x: lielab.domain.CompositeAlgebra, y: lielab.domain.CompositeAlgebra, power: int = 1) -> lielab.domain.CompositeAlgebra: ...

@overload
def coad(x: lielab.domain.cn, power: int = 1) -> lielab.domain.glr: ...
@overload
def coad(x: lielab.domain.cn, y: lielab.domain.cn, power: int = 1) -> lielab.domain.cn: ...
@overload
def coad(x: lielab.domain.glc, power: int = 1) -> lielab.domain.glr: ...
@overload
def coad(x: lielab.domain.glc, y: lielab.domain.glc, power: int = 1) -> lielab.domain.glc: ...
@overload
def coad(x: lielab.domain.glr, power: int = 1) -> lielab.domain.glr: ...
@overload
def coad(x: lielab.domain.glr, y: lielab.domain.glr, power: int = 1) -> lielab.domain.glr: ...
@overload
def coad(x: lielab.domain.rn, power: int = 1) -> lielab.domain.glr: ...
@overload
def coad(x: lielab.domain.rn, y: lielab.domain.rn, power: int = 1) -> lielab.domain.rn: ...
@overload
def coad(x: lielab.domain.se, power: int = 1) -> lielab.domain.glr: ...
@overload
def coad(x: lielab.domain.se, y: lielab.domain.se, power: int = 1) -> lielab.domain.se: ...
@overload
def coad(x: lielab.domain.so, power: int = 1) -> lielab.domain.glr: ...
@overload
def coad(x: lielab.domain.so, y: lielab.domain.so, power: int = 1) -> lielab.domain.so: ...
@overload
def coad(x: lielab.domain.sp, power: int = 1) -> lielab.domain.glr: ...
@overload
def coad(x: lielab.domain.sp, y: lielab.domain.sp, power: int = 1) -> lielab.domain.sp: ...
@overload
def coad(x: lielab.domain.su, power: int = 1) -> lielab.domain.glr: ...
@overload
def coad(x: lielab.domain.su, y: lielab.domain.su, power: int = 1) -> lielab.domain.su: ...
@overload
def coad(x: lielab.domain.CompositeAlgebra, power: int = 1) -> lielab.domain.CompositeAlgebra: ...
@overload
def coad(x: lielab.domain.CompositeAlgebra, y: lielab.domain.CompositeAlgebra, power: int = 1) -> lielab.domain.CompositeAlgebra: ...


# Ad
@overload
def Ad(x: lielab.domain.CN, y: lielab.domain.cn) -> lielab.domain.cn: ...
@overload
def Ad(x: lielab.domain.GLC, y: lielab.domain.glc) -> lielab.domain.glc: ...
@overload
def Ad(x: lielab.domain.GLR, y: lielab.domain.glr) -> lielab.domain.glr: ...
@overload
def Ad(x: lielab.domain.RN, y: lielab.domain.rn) -> lielab.domain.rn: ...
@overload
def Ad(x: lielab.domain.SE, y: lielab.domain.se) -> lielab.domain.se: ...
@overload
def Ad(x: lielab.domain.SO, y: lielab.domain.so) -> lielab.domain.so: ...
@overload
def Ad(x: lielab.domain.SP, y: lielab.domain.sp) -> lielab.domain.sp: ...
@overload
def Ad(x: lielab.domain.SU, y: lielab.domain.su) -> lielab.domain.su: ...
@overload
def Ad(x: lielab.domain.CompositeGroup, y: lielab.domain.CompositeAlgebra) -> lielab.domain.CompositeAlgebra: ...

