from typing import overload, TYPE_CHECKING

if TYPE_CHECKING:
    import lielab

# cay
@overload
def cay(x: lielab.domain.cn) -> lielab.domain.CN: ...
@overload
def cay(x: lielab.domain.glc) -> lielab.domain.GLC: ...
@overload
def cay(x: lielab.domain.glr) -> lielab.domain.GLR: ...
@overload
def cay(x: lielab.domain.rn) -> lielab.domain.RN: ...
@overload
def cay(x: lielab.domain.se) -> lielab.domain.SE: ...
@overload
def cay(x: lielab.domain.so) -> lielab.domain.SO: ...
@overload
def cay(x: lielab.domain.sp) -> lielab.domain.SP: ...
@overload
def cay(x: lielab.domain.su) -> lielab.domain.SU: ...
@overload
def cay(x: lielab.domain.CompositeAlgebra) -> lielab.domain.CompositeGroup: ...

# cayinv
@overload
def cayinv(x: lielab.domain.CN) -> lielab.domain.cn: ...
@overload
def cayinv(x: lielab.domain.GLC) -> lielab.domain.glc: ...
@overload
def cayinv(x: lielab.domain.GLR) -> lielab.domain.glr: ...
@overload
def cayinv(x: lielab.domain.RN) -> lielab.domain.rn: ...
@overload
def cayinv(x: lielab.domain.SE) -> lielab.domain.se: ...
@overload
def cayinv(x: lielab.domain.SO) -> lielab.domain.so: ...
@overload
def cayinv(x: lielab.domain.SP) -> lielab.domain.sp: ...
@overload
def cayinv(x: lielab.domain.SU) -> lielab.domain.su: ...
@overload
def cayinv(x: lielab.domain.CompositeGroup) -> lielab.domain.CompositeAlgebra: ...

# dcay
# @overload
# def dcay(x: lielab.domain.cn) -> lielab.domain.glr: ...
# @overload
# def dcay(x: lielab.domain.glc) -> lielab.domain.glr: ...
# @overload
# def dcay(x: lielab.domain.glr) -> lielab.domain.glr: ...
# @overload
# def dcay(x: lielab.domain.rn) -> lielab.domain.glr: ...
# @overload
# def dcay(x: lielab.domain.se) -> lielab.domain.glr: ...
# @overload
# def dcay(x: lielab.domain.so) -> lielab.domain.glr: ...
# @overload
# def dcay(x: lielab.domain.sp) -> lielab.domain.glr: ...
# @overload
# def dcay(x: lielab.domain.su) -> lielab.domain.glr: ...
# @overload
# def dcay(x: lielab.domain.CompositeAlgebra) -> lielab.domain.CompositeAlgebra: ...

@overload
def dcay(x: lielab.domain.cn, y: lielab.domain.cn) -> lielab.domain.cn: ...
@overload
def dcay(x: lielab.domain.glc, y: lielab.domain.glc) -> lielab.domain.glc: ...
@overload
def dcay(x: lielab.domain.glr, y: lielab.domain.glr) -> lielab.domain.glr: ...
@overload
def dcay(x: lielab.domain.rn, y: lielab.domain.rn) -> lielab.domain.rn: ...
@overload
def dcay(x: lielab.domain.se, y: lielab.domain.se) -> lielab.domain.se: ...
@overload
def dcay(x: lielab.domain.so, y: lielab.domain.so) -> lielab.domain.so: ...
@overload
def dcay(x: lielab.domain.sp, y: lielab.domain.sp) -> lielab.domain.sp: ...
@overload
def dcay(x: lielab.domain.su, y: lielab.domain.su) -> lielab.domain.su: ...
@overload
def dcay(x: lielab.domain.CompositeAlgebra, y: lielab.domain.CompositeAlgebra) -> lielab.domain.CompositeAlgebra: ...

# dexpinv
# @overload
# def dcayinv(x: lielab.domain.cn) -> lielab.domain.glr: ...
# @overload
# def dcayinv(x: lielab.domain.glc) -> lielab.domain.glr: ...
# @overload
# def dcayinv(x: lielab.domain.glr) -> lielab.domain.glr: ...
# @overload
# def dcayinv(x: lielab.domain.rn) -> lielab.domain.glr: ...
# @overload
# def dcayinv(x: lielab.domain.se) -> lielab.domain.glr: ...
# @overload
# def dcayinv(x: lielab.domain.so) -> lielab.domain.glr: ...
# @overload
# def dcayinv(x: lielab.domain.sp) -> lielab.domain.glr: ...
# @overload
# def dcayinv(x: lielab.domain.su) -> lielab.domain.glr: ...
# @overload
# def dcayinv(x: lielab.domain.CompositeAlgebra) -> lielab.domain.CompositeAlgebra: ...

@overload
def dcayinv(x: lielab.domain.cn, y: lielab.domain.cn) -> lielab.domain.cn: ...
@overload
def dcayinv(x: lielab.domain.glc, y: lielab.domain.glc) -> lielab.domain.glc: ...
@overload
def dcayinv(x: lielab.domain.glr, y: lielab.domain.glr) -> lielab.domain.glr: ...
@overload
def dcayinv(x: lielab.domain.rn, y: lielab.domain.rn) -> lielab.domain.rn: ...
@overload
def dcayinv(x: lielab.domain.se, y: lielab.domain.se) -> lielab.domain.se: ...
@overload
def dcayinv(x: lielab.domain.so, y: lielab.domain.so) -> lielab.domain.so: ...
@overload
def dcayinv(x: lielab.domain.sp, y: lielab.domain.sp) -> lielab.domain.sp: ...
@overload
def dcayinv(x: lielab.domain.su, y: lielab.domain.su) -> lielab.domain.su: ...
@overload
def dcayinv(x: lielab.domain.CompositeAlgebra, y: lielab.domain.CompositeAlgebra) -> lielab.domain.CompositeAlgebra: ...

# cay2
@overload
def cay2(x: lielab.domain.cn) -> lielab.domain.CN: ...
@overload
def cay2(x: lielab.domain.glc) -> lielab.domain.GLC: ...
@overload
def cay2(x: lielab.domain.glr) -> lielab.domain.GLR: ...
@overload
def cay2(x: lielab.domain.rn) -> lielab.domain.RN: ...
@overload
def cay2(x: lielab.domain.se) -> lielab.domain.SE: ...
@overload
def cay2(x: lielab.domain.so) -> lielab.domain.SO: ...
@overload
def cay2(x: lielab.domain.sp) -> lielab.domain.SP: ...
@overload
def cay2(x: lielab.domain.su) -> lielab.domain.SU: ...
@overload
def cay2(x: lielab.domain.CompositeAlgebra) -> lielab.domain.CompositeGroup: ...
