from typing import overload, TYPE_CHECKING

if TYPE_CHECKING:
    import numpy.typing as npt
    import numpy as np
    import lielab

# exp
@overload
def exp_numerical(x: lielab.domain.cn) -> lielab.domain.CN: ...
@overload
def exp_numerical(x: lielab.domain.glc) -> lielab.domain.GLC: ...
@overload
def exp_numerical(x: lielab.domain.glr) -> lielab.domain.GLR: ...
@overload
def exp_numerical(x: lielab.domain.rn) -> lielab.domain.RN: ...
@overload
def exp_numerical(x: lielab.domain.se) -> lielab.domain.SE: ...
@overload
def exp_numerical(x: lielab.domain.so) -> lielab.domain.SO: ...
@overload
def exp_numerical(x: lielab.domain.sp) -> lielab.domain.SP: ...
@overload
def exp_numerical(x: lielab.domain.su) -> lielab.domain.SU: ...
@overload
def exp_numerical(x: lielab.domain.CompositeAlgebra) -> lielab.domain.CompositeGroup: ...

@overload
def exp(x: lielab.domain.cn) -> lielab.domain.CN: ...
@overload
def exp(x: lielab.domain.glc) -> lielab.domain.GLC: ...
@overload
def exp(x: lielab.domain.glr) -> lielab.domain.GLR: ...
@overload
def exp(x: lielab.domain.rn) -> lielab.domain.RN: ...
@overload
def exp(x: lielab.domain.se) -> lielab.domain.SE: ...
@overload
def exp(x: lielab.domain.so) -> lielab.domain.SO: ...
@overload
def exp(x: lielab.domain.sp) -> lielab.domain.SP: ...
@overload
def exp(x: lielab.domain.su) -> lielab.domain.SU: ...
@overload
def exp(x: lielab.domain.CompositeAlgebra) -> lielab.domain.CompositeGroup: ...

# dexp
@overload
def dexp_numerical(x: lielab.domain.cn) -> lielab.domain.glr: ...
@overload
def dexp_numerical(x: lielab.domain.cn, y: lielab.domain.cn) -> lielab.domain.cn: ...
@overload
def dexp_numerical(x: lielab.domain.glc) -> lielab.domain.glr: ...
@overload
def dexp_numerical(x: lielab.domain.glc, y: lielab.domain.glc) -> lielab.domain.glc: ...
@overload
def dexp_numerical(x: lielab.domain.glr) -> lielab.domain.glr: ...
@overload
def dexp_numerical(x: lielab.domain.glr, y: lielab.domain.glr) -> lielab.domain.glr: ...
@overload
def dexp_numerical(x: lielab.domain.rn) -> lielab.domain.glr: ...
@overload
def dexp_numerical(x: lielab.domain.rn, y: lielab.domain.rn) -> lielab.domain.rn: ...
@overload
def dexp_numerical(x: lielab.domain.se) -> lielab.domain.glr: ...
@overload
def dexp_numerical(x: lielab.domain.se, y: lielab.domain.se) -> lielab.domain.se: ...
@overload
def dexp_numerical(x: lielab.domain.so) -> lielab.domain.glr: ...
@overload
def dexp_numerical(x: lielab.domain.so, y: lielab.domain.so) -> lielab.domain.so: ...
@overload
def dexp_numerical(x: lielab.domain.sp) -> lielab.domain.glr: ...
@overload
def dexp_numerical(x: lielab.domain.sp, y: lielab.domain.sp) -> lielab.domain.sp: ...
@overload
def dexp_numerical(x: lielab.domain.su) -> lielab.domain.glr: ...
@overload
def dexp_numerical(x: lielab.domain.su, y: lielab.domain.su) -> lielab.domain.su: ...
@overload
def dexp_numerical(x: lielab.domain.CompositeAlgebra) -> lielab.domain.CompositeAlgebra: ...
@overload
def dexp_numerical(x: lielab.domain.CompositeAlgebra, y: lielab.domain.CompositeAlgebra) -> lielab.domain.CompositeAlgebra: ...

@overload
def dexp(x: lielab.domain.cn) -> lielab.domain.glr: ...
@overload
def dexp(x: lielab.domain.cn, y: lielab.domain.cn) -> lielab.domain.cn: ...
@overload
def dexp(x: lielab.domain.glc) -> lielab.domain.glr: ...
@overload
def dexp(x: lielab.domain.glc, y: lielab.domain.glc) -> lielab.domain.glc: ...
@overload
def dexp(x: lielab.domain.glr) -> lielab.domain.glr: ...
@overload
def dexp(x: lielab.domain.glr, y: lielab.domain.glr) -> lielab.domain.glr: ...
@overload
def dexp(x: lielab.domain.rn) -> lielab.domain.glr: ...
@overload
def dexp(x: lielab.domain.rn, y: lielab.domain.rn) -> lielab.domain.rn: ...
@overload
def dexp(x: lielab.domain.se) -> lielab.domain.glr: ...
@overload
def dexp(x: lielab.domain.se, y: lielab.domain.se) -> lielab.domain.se: ...
@overload
def dexp(x: lielab.domain.so) -> lielab.domain.glr: ...
@overload
def dexp(x: lielab.domain.so, y: lielab.domain.so) -> lielab.domain.so: ...
@overload
def dexp(x: lielab.domain.sp) -> lielab.domain.glr: ...
@overload
def dexp(x: lielab.domain.sp, y: lielab.domain.sp) -> lielab.domain.sp: ...
@overload
def dexp(x: lielab.domain.su) -> lielab.domain.glr: ...
@overload
def dexp(x: lielab.domain.su, y: lielab.domain.su) -> lielab.domain.su: ...
@overload
def dexp(x: lielab.domain.CompositeAlgebra) -> lielab.domain.CompositeAlgebra: ...
@overload
def dexp(x: lielab.domain.CompositeAlgebra, y: lielab.domain.CompositeAlgebra) -> lielab.domain.CompositeAlgebra: ...

# dexpinv
@overload
def dexpinv_numerical(x: lielab.domain.cn) -> lielab.domain.glr: ...
@overload
def dexpinv_numerical(x: lielab.domain.cn, y: lielab.domain.cn) -> lielab.domain.cn: ...
@overload
def dexpinv_numerical(x: lielab.domain.glc) -> lielab.domain.glr: ...
@overload
def dexpinv_numerical(x: lielab.domain.glc, y: lielab.domain.glc) -> lielab.domain.glc: ...
@overload
def dexpinv_numerical(x: lielab.domain.glr) -> lielab.domain.glr: ...
@overload
def dexpinv_numerical(x: lielab.domain.glr, y: lielab.domain.glr) -> lielab.domain.glr: ...
@overload
def dexpinv_numerical(x: lielab.domain.rn) -> lielab.domain.glr: ...
@overload
def dexpinv_numerical(x: lielab.domain.rn, y: lielab.domain.rn) -> lielab.domain.rn: ...
@overload
def dexpinv_numerical(x: lielab.domain.se) -> lielab.domain.glr: ...
@overload
def dexpinv_numerical(x: lielab.domain.se, y: lielab.domain.se) -> lielab.domain.se: ...
@overload
def dexpinv_numerical(x: lielab.domain.so) -> lielab.domain.glr: ...
@overload
def dexpinv_numerical(x: lielab.domain.so, y: lielab.domain.so) -> lielab.domain.so: ...
@overload
def dexpinv_numerical(x: lielab.domain.sp) -> lielab.domain.glr: ...
@overload
def dexpinv_numerical(x: lielab.domain.sp, y: lielab.domain.sp) -> lielab.domain.sp: ...
@overload
def dexpinv_numerical(x: lielab.domain.su) -> lielab.domain.glr: ...
@overload
def dexpinv_numerical(x: lielab.domain.su, y: lielab.domain.su) -> lielab.domain.su: ...
@overload
def dexpinv_numerical(x: lielab.domain.CompositeAlgebra) -> lielab.domain.CompositeAlgebra: ...
@overload
def dexpinv_numerical(x: lielab.domain.CompositeAlgebra, y: lielab.domain.CompositeAlgebra) -> lielab.domain.CompositeAlgebra: ...

@overload
def dexpinv(x: lielab.domain.cn) -> lielab.domain.glr: ...
@overload
def dexpinv(x: lielab.domain.cn, y: lielab.domain.cn) -> lielab.domain.cn: ...
@overload
def dexpinv(x: lielab.domain.glc) -> lielab.domain.glr: ...
@overload
def dexpinv(x: lielab.domain.glc, y: lielab.domain.glc) -> lielab.domain.glc: ...
@overload
def dexpinv(x: lielab.domain.glr) -> lielab.domain.glr: ...
@overload
def dexpinv(x: lielab.domain.glr, y: lielab.domain.glr) -> lielab.domain.glr: ...
@overload
def dexpinv(x: lielab.domain.rn) -> lielab.domain.glr: ...
@overload
def dexpinv(x: lielab.domain.rn, y: lielab.domain.rn) -> lielab.domain.rn: ...
@overload
def dexpinv(x: lielab.domain.se) -> lielab.domain.glr: ...
@overload
def dexpinv(x: lielab.domain.se, y: lielab.domain.se) -> lielab.domain.se: ...
@overload
def dexpinv(x: lielab.domain.so) -> lielab.domain.glr: ...
@overload
def dexpinv(x: lielab.domain.so, y: lielab.domain.so) -> lielab.domain.so: ...
@overload
def dexpinv(x: lielab.domain.sp) -> lielab.domain.glr: ...
@overload
def dexpinv(x: lielab.domain.sp, y: lielab.domain.sp) -> lielab.domain.sp: ...
@overload
def dexpinv(x: lielab.domain.su) -> lielab.domain.glr: ...
@overload
def dexpinv(x: lielab.domain.su, y: lielab.domain.su) -> lielab.domain.su: ...
@overload
def dexpinv(x: lielab.domain.CompositeAlgebra) -> lielab.domain.CompositeAlgebra: ...
@overload
def dexpinv(x: lielab.domain.CompositeAlgebra, y: lielab.domain.CompositeAlgebra) -> lielab.domain.CompositeAlgebra: ...

# log
@overload
def log_numerical(x: lielab.domain.CN) -> lielab.domain.cn: ...
@overload
def log_numerical(x: lielab.domain.GLC) -> lielab.domain.glc: ...
@overload
def log_numerical(x: lielab.domain.GLR) -> lielab.domain.glr: ...
@overload
def log_numerical(x: lielab.domain.RN) -> lielab.domain.rn: ...
@overload
def log_numerical(x: lielab.domain.SE) -> lielab.domain.se: ...
@overload
def log_numerical(x: lielab.domain.SO) -> lielab.domain.so: ...
@overload
def log_numerical(x: lielab.domain.SP) -> lielab.domain.sp: ...
@overload
def log_numerical(x: lielab.domain.SU) -> lielab.domain.su: ...
@overload
def log_numerical(x: lielab.domain.CompositeGroup) -> lielab.domain.CompositeAlgebra: ...

@overload
def log(x: lielab.domain.CN) -> lielab.domain.cn: ...
@overload
def log(x: lielab.domain.GLC) -> lielab.domain.glc: ...
@overload
def log(x: lielab.domain.GLR) -> lielab.domain.glr: ...
@overload
def log(x: lielab.domain.RN) -> lielab.domain.rn: ...
@overload
def log(x: lielab.domain.SE) -> lielab.domain.se: ...
@overload
def log(x: lielab.domain.SO) -> lielab.domain.so: ...
@overload
def log(x: lielab.domain.SP) -> lielab.domain.sp: ...
@overload
def log(x: lielab.domain.SU) -> lielab.domain.su: ...
@overload
def log(x: lielab.domain.CompositeGroup) -> lielab.domain.CompositeAlgebra: ...

# dlog
@overload
def dlog_numerical(x: lielab.domain.cn) -> lielab.domain.glr: ...
@overload
def dlog_numerical(x: lielab.domain.cn, y: lielab.domain.cn) -> lielab.domain.cn: ...
@overload
def dlog_numerical(x: lielab.domain.glc) -> lielab.domain.glr: ...
@overload
def dlog_numerical(x: lielab.domain.glc, y: lielab.domain.glc) -> lielab.domain.glc: ...
@overload
def dlog_numerical(x: lielab.domain.glr) -> lielab.domain.glr: ...
@overload
def dlog_numerical(x: lielab.domain.glr, y: lielab.domain.glr) -> lielab.domain.glr: ...
@overload
def dlog_numerical(x: lielab.domain.rn) -> lielab.domain.glr: ...
@overload
def dlog_numerical(x: lielab.domain.rn, y: lielab.domain.rn) -> lielab.domain.rn: ...
@overload
def dlog_numerical(x: lielab.domain.se) -> lielab.domain.glr: ...
@overload
def dlog_numerical(x: lielab.domain.se, y: lielab.domain.se) -> lielab.domain.se: ...
@overload
def dlog_numerical(x: lielab.domain.so) -> lielab.domain.glr: ...
@overload
def dlog_numerical(x: lielab.domain.so, y: lielab.domain.so) -> lielab.domain.so: ...
@overload
def dlog_numerical(x: lielab.domain.sp) -> lielab.domain.glr: ...
@overload
def dlog_numerical(x: lielab.domain.sp, y: lielab.domain.sp) -> lielab.domain.sp: ...
@overload
def dlog_numerical(x: lielab.domain.su) -> lielab.domain.glr: ...
@overload
def dlog_numerical(x: lielab.domain.su, y: lielab.domain.su) -> lielab.domain.su: ...
@overload
def dlog_numerical(x: lielab.domain.CompositeAlgebra) -> lielab.domain.CompositeAlgebra: ...
@overload
def dlog_numerical(x: lielab.domain.CompositeAlgebra, y: lielab.domain.CompositeAlgebra) -> lielab.domain.CompositeAlgebra: ...

@overload
def dlog(x: lielab.domain.cn) -> lielab.domain.glr: ...
@overload
def dlog(x: lielab.domain.cn, y: lielab.domain.cn) -> lielab.domain.cn: ...
@overload
def dlog(x: lielab.domain.glc) -> lielab.domain.glr: ...
@overload
def dlog(x: lielab.domain.glc, y: lielab.domain.glc) -> lielab.domain.glc: ...
@overload
def dlog(x: lielab.domain.glr) -> lielab.domain.glr: ...
@overload
def dlog(x: lielab.domain.glr, y: lielab.domain.glr) -> lielab.domain.glr: ...
@overload
def dlog(x: lielab.domain.rn) -> lielab.domain.glr: ...
@overload
def dlog(x: lielab.domain.rn, y: lielab.domain.rn) -> lielab.domain.rn: ...
@overload
def dlog(x: lielab.domain.se) -> lielab.domain.glr: ...
@overload
def dlog(x: lielab.domain.se, y: lielab.domain.se) -> lielab.domain.se: ...
@overload
def dlog(x: lielab.domain.so) -> lielab.domain.glr: ...
@overload
def dlog(x: lielab.domain.so, y: lielab.domain.so) -> lielab.domain.so: ...
@overload
def dlog(x: lielab.domain.sp) -> lielab.domain.glr: ...
@overload
def dlog(x: lielab.domain.sp, y: lielab.domain.sp) -> lielab.domain.sp: ...
@overload
def dlog(x: lielab.domain.su) -> lielab.domain.glr: ...
@overload
def dlog(x: lielab.domain.su, y: lielab.domain.su) -> lielab.domain.su: ...
@overload
def dlog(x: lielab.domain.CompositeAlgebra) -> lielab.domain.CompositeAlgebra: ...
@overload
def dlog(x: lielab.domain.CompositeAlgebra, y: lielab.domain.CompositeAlgebra) -> lielab.domain.CompositeAlgebra: ...

# dloginv
@overload
def dloginv_numerical(x: lielab.domain.cn) -> lielab.domain.glr: ...
@overload
def dloginv_numerical(x: lielab.domain.cn, y: lielab.domain.cn) -> lielab.domain.cn: ...
@overload
def dloginv_numerical(x: lielab.domain.glc) -> lielab.domain.glr: ...
@overload
def dloginv_numerical(x: lielab.domain.glc, y: lielab.domain.glc) -> lielab.domain.glc: ...
@overload
def dloginv_numerical(x: lielab.domain.glr) -> lielab.domain.glr: ...
@overload
def dloginv_numerical(x: lielab.domain.glr, y: lielab.domain.glr) -> lielab.domain.glr: ...
@overload
def dloginv_numerical(x: lielab.domain.rn) -> lielab.domain.glr: ...
@overload
def dloginv_numerical(x: lielab.domain.rn, y: lielab.domain.rn) -> lielab.domain.rn: ...
@overload
def dloginv_numerical(x: lielab.domain.se) -> lielab.domain.glr: ...
@overload
def dloginv_numerical(x: lielab.domain.se, y: lielab.domain.se) -> lielab.domain.se: ...
@overload
def dloginv_numerical(x: lielab.domain.so) -> lielab.domain.glr: ...
@overload
def dloginv_numerical(x: lielab.domain.so, y: lielab.domain.so) -> lielab.domain.so: ...
@overload
def dloginv_numerical(x: lielab.domain.sp) -> lielab.domain.glr: ...
@overload
def dloginv_numerical(x: lielab.domain.sp, y: lielab.domain.sp) -> lielab.domain.sp: ...
@overload
def dloginv_numerical(x: lielab.domain.su) -> lielab.domain.glr: ...
@overload
def dloginv_numerical(x: lielab.domain.su, y: lielab.domain.su) -> lielab.domain.su: ...
@overload
def dloginv_numerical(x: lielab.domain.CompositeAlgebra) -> lielab.domain.CompositeAlgebra: ...
@overload
def dloginv_numerical(x: lielab.domain.CompositeAlgebra, y: lielab.domain.CompositeAlgebra) -> lielab.domain.CompositeAlgebra: ...

@overload
def dloginv(x: lielab.domain.cn) -> lielab.domain.glr: ...
@overload
def dloginv(x: lielab.domain.cn, y: lielab.domain.cn) -> lielab.domain.cn: ...
@overload
def dloginv(x: lielab.domain.glc) -> lielab.domain.glr: ...
@overload
def dloginv(x: lielab.domain.glc, y: lielab.domain.glc) -> lielab.domain.glc: ...
@overload
def dloginv(x: lielab.domain.glr) -> lielab.domain.glr: ...
@overload
def dloginv(x: lielab.domain.glr, y: lielab.domain.glr) -> lielab.domain.glr: ...
@overload
def dloginv(x: lielab.domain.rn) -> lielab.domain.glr: ...
@overload
def dloginv(x: lielab.domain.rn, y: lielab.domain.rn) -> lielab.domain.rn: ...
@overload
def dloginv(x: lielab.domain.se) -> lielab.domain.glr: ...
@overload
def dloginv(x: lielab.domain.se, y: lielab.domain.se) -> lielab.domain.se: ...
@overload
def dloginv(x: lielab.domain.so) -> lielab.domain.glr: ...
@overload
def dloginv(x: lielab.domain.so, y: lielab.domain.so) -> lielab.domain.so: ...
@overload
def dloginv(x: lielab.domain.sp) -> lielab.domain.glr: ...
@overload
def dloginv(x: lielab.domain.sp, y: lielab.domain.sp) -> lielab.domain.sp: ...
@overload
def dloginv(x: lielab.domain.su) -> lielab.domain.glr: ...
@overload
def dloginv(x: lielab.domain.su, y: lielab.domain.su) -> lielab.domain.su: ...
@overload
def dloginv(x: lielab.domain.CompositeAlgebra) -> lielab.domain.CompositeAlgebra: ...
@overload
def dloginv(x: lielab.domain.CompositeAlgebra, y: lielab.domain.CompositeAlgebra) -> lielab.domain.CompositeAlgebra: ...
