from typing import TYPE_CHECKING, overload

if TYPE_CHECKING:
    import numpy.typing as npt
    import numpy as np
    from lielab.domain import CompositeManifold, CompositeGroup, CompositeAlgebra

@overload
def check_topology(a: CompositeManifold, b: CompositeManifold) -> bool: ...
@overload
def check_topology(a: CompositeGroup, b: CompositeGroup) -> bool: ...
@overload
def check_topology(a: CompositeAlgebra, b: CompositeAlgebra) -> bool: ...

@overload
def check_almost_equal_tol(a: float, b: float, abstol: float = 1.0e-14, reltol: float = 1.0e-14) -> bool: ...
@overload
def check_almost_equal_tol(a: npt.NDArray[np.floating], b: npt.NDArray[np.floating], abstol: float = 1.0e-14, reltol: float = 1.0e-14) -> bool: ...
@overload
def check_almost_equal_tol(a: npt.NDArray[np.complexfloating], b: npt.NDArray[np.complexfloating], abstol: float = 1.0e-14, reltol: float = 1.0e-14) -> bool: ...
@overload
def check_almost_equal_tol(a: CompositeManifold, b: CompositeManifold, abstol: float = 1.0e-14, reltol: float = 1.0e-14) -> bool: ...
@overload
def check_almost_equal_tol(a: CompositeGroup, b: CompositeGroup, abstol: float = 1.0e-14, reltol: float = 1.0e-14) -> bool: ...
@overload
def check_almost_equal_tol(a: CompositeAlgebra, b: CompositeAlgebra, abstol: float = 1.0e-14, reltol: float = 1.0e-14) -> bool: ...

@overload
def check_almost_equal_nulp(a: float, b: float, nulp: int = 1, gate: bool = False) -> bool: ...
@overload
def check_almost_equal_nulp(a: npt.NDArray[np.floating], b: npt.NDArray[np.floating], nulp: int = 1, gate: bool = False) -> bool: ...
@overload
def check_almost_equal_nulp(a: npt.NDArray[np.complexfloating], b: npt.NDArray[np.complexfloating], nulp: int = 1, gate: bool = False) -> bool: ...
@overload
def check_almost_equal_nulp(a: CompositeManifold, b: CompositeManifold, nulp: int = 1, gate: bool = False) -> bool: ...
@overload
def check_almost_equal_nulp(a: CompositeGroup, b: CompositeGroup, nulp: int = 1, gate: bool = False) -> bool: ...
@overload
def check_almost_equal_nulp(a: CompositeAlgebra, b: CompositeAlgebra, nulp: int = 1, gate: bool = False) -> bool: ...
