from typing import overload, TYPE_CHECKING

if TYPE_CHECKING:
    import numpy.typing as npt
    import numpy as np

class CN:
    point: npt.NDArray[np.floating]

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, matrix: npt.NDArray[np.complexfloating]) -> None: ...
    @staticmethod
    def identity(shape: int) -> CN: ...
    @staticmethod
    def project(matrix: npt.NDArray[np.complexfloating]) -> CN: ...
    @overload
    def __init__(self, n: int) -> None: ...
    @staticmethod
    def from_vector(vector: npt.NDArray[np.floating]) -> CN: ...
    @staticmethod
    def from_complex_vector(vector: npt.NDArray[np.complexfloating]) -> CN: ...
    def to_string(self) -> str: ...
    def get_dimension(self) -> int: ...
    def get_size(self) -> int: ...
    def is_abelian(self) -> bool: ...
    def get_shape(self) -> int: ...
    def get_point(self) -> npt.NDArray[np.floating]: ...
    def serialize(self) -> npt.NDArray[np.floating]: ...
    def unserialize(self, serialized: npt.NDArray[np.floating]) -> None: ...
    def get_matrix(self) -> npt.NDArray[np.complexfloating]: ...
    @overload
    def __call__(self, index1: int, index2: int) -> complex: ...
    def to_complex_vector(self) -> npt.NDArray[np.complexfloating]: ...
    # operator[]
    def inverse(self) -> CN: ...
