from typing import overload, TYPE_CHECKING, List

if TYPE_CHECKING:
    from lielab.domain import *
    import numpy.typing as npt
    import numpy as np

class CompositeGroup:
    point: list[CN | GLC | GLR | RN | SE | SO | SP | SU]

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, matrix: npt.NDArray[np.complexfloating]) -> None: ...
    @staticmethod
    def identity(shape: int) -> CompositeGroup: ...
    @staticmethod
    def project(matrix: npt.NDArray[np.complexfloating]) -> CompositeGroup: ...
    @overload
    def __init__(self, n: int) -> None: ...
    overload
    def __init__(self, lie_groups: list[CN | GLC | GLR | RN | SE | SO | SP | SU]) -> None: ...
    def to_string(self) -> str: ...
    def get_dimension(self) -> int: ...
    def get_size(self) -> int: ...
    def is_abelian(self) -> bool: ...
    def get_shape(self) -> int: ...
    def get_dimensions(self) -> List[int]: ...
    def get_sizes(self) -> List[int]: ...
    def get_shapes(self) -> List[int]: ...
    def get_point(self) -> list[CN | GLC | GLR | RN | SE | SO | SP | SU]: ...
    def serialize(self) -> npt.NDArray[np.floating]: ...
    def unserialize(self, serialized: npt.NDArray[np.floating]) -> None: ...
    def get_matrix(self) -> npt.NDArray[np.complexfloating]: ...
    @overload
    def __call__(self, index1: int, index2: int) -> complex: ...
    def inverse(self) -> CompositeGroup: ...
