from typing import overload, TYPE_CHECKING, Tuple

if TYPE_CHECKING:
    import numpy.typing as npt
    import numpy as np
    from lielab.domain import RN, SO

class SE:
    point: Tuple[RN, SO]

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, matrix: npt.NDArray[np.floating]) -> None: ...
    @staticmethod
    def identity(shape: int) -> SE: ...
    @staticmethod
    def project(matrix: npt.NDArray[np.floating]) -> SE: ...
    @overload
    def __init__(self, n: int) -> None: ...
    @overload
    def __init__(self, RN_component: RN, SO_component: SO) -> None: ...
    def to_string(self) -> str: ...
    def get_dimension(self) -> int: ...
    def get_size(self) -> int: ...
    def is_abelian(self) -> bool: ...
    def get_shape(self) -> int: ...
    def get_point(self) -> Tuple[RN, SO]: ...
    def serialize(self) -> npt.NDArray[np.floating]: ...
    def unserialize(self, vector: npt.NDArray[np.floating]) -> None: ...
    def get_matrix(self) -> npt.NDArray[np.floating]: ...
    @overload
    def __call__(self, index1: int, index2: int) -> float: ...
    def inverse(self) -> SE: ...
