from typing import overload, TYPE_CHECKING

if TYPE_CHECKING:
    from lielab.domain import SU
    import numpy.typing as npt
    import numpy as np

class SO:
    point: npt.NDArray[np.floating]

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, matrix: npt.NDArray[np.floating]) -> None: ...
    @staticmethod
    def identity(shape: int) -> SO: ...
    @staticmethod
    def project(matrix: npt.NDArray[np.floating]) -> SO: ...
    @overload
    def __init__(self, n: int) -> None: ...
    @staticmethod
    def from_eulerangles_body123(theta1: float, theta2: float, theta3: float) -> SO: ...
    @staticmethod
    def from_eulerangles_body231(theta1: float, theta2: float, theta3: float) -> SO: ...
    @staticmethod
    def from_eulerangles_body312(theta1: float, theta2: float, theta3: float) -> SO: ...
    @staticmethod
    def from_eulerangles_body132(theta1: float, theta2: float, theta3: float) -> SO: ...
    @staticmethod
    def from_eulerangles_body213(theta1: float, theta2: float, theta3: float) -> SO: ...
    @staticmethod
    def from_eulerangles_body321(theta1: float, theta2: float, theta3: float) -> SO: ...
    @staticmethod
    def from_eulerangles_body121(theta1: float, theta2: float, theta3: float) -> SO: ...
    @staticmethod
    def from_eulerangles_body131(theta1: float, theta2: float, theta3: float) -> SO: ...
    @staticmethod
    def from_eulerangles_body212(theta1: float, theta2: float, theta3: float) -> SO: ...
    @staticmethod
    def from_eulerangles_body232(theta1: float, theta2: float, theta3: float) -> SO: ...
    @staticmethod
    def from_eulerangles_body313(theta1: float, theta2: float, theta3: float) -> SO: ...
    @staticmethod
    def from_eulerangles_body323(theta1: float, theta2: float, theta3: float) -> SO: ...
    @staticmethod
    def from_eulerangles_space123(theta1: float, theta2: float, theta3: float) -> SO: ...
    @staticmethod
    def from_eulerangles_space231(theta1: float, theta2: float, theta3: float) -> SO: ...
    @staticmethod
    def from_eulerangles_space312(theta1: float, theta2: float, theta3: float) -> SO: ...
    @staticmethod
    def from_eulerangles_space132(theta1: float, theta2: float, theta3: float) -> SO: ...
    @staticmethod
    def from_eulerangles_space213(theta1: float, theta2: float, theta3: float) -> SO: ...
    @staticmethod
    def from_eulerangles_space321(theta1: float, theta2: float, theta3: float) -> SO: ...
    @staticmethod
    def from_eulerangles_space121(theta1: float, theta2: float, theta3: float) -> SO: ...
    @staticmethod
    def from_eulerangles_space131(theta1: float, theta2: float, theta3: float) -> SO: ...
    @staticmethod
    def from_eulerangles_space212(theta1: float, theta2: float, theta3: float) -> SO: ...
    @staticmethod
    def from_eulerangles_space232(theta1: float, theta2: float, theta3: float) -> SO: ...
    @staticmethod
    def from_eulerangles_space313(theta1: float, theta2: float, theta3: float) -> SO: ...
    @staticmethod
    def from_eulerangles_space323(theta1: float, theta2: float, theta3: float) -> SO: ...
    @staticmethod
    def from_quaternion(e0: float, e1: float, e2: float, e3: float) -> SO: ...
    @staticmethod
    def from_rodriguesvector(g1: float, g2: float, g3: float) -> SO: ...
    @staticmethod
    def from_SU2(g: SU) -> SO: ...
    def to_string(self) -> str: ...
    def get_size(self) -> int: ...
    def is_abelian(self) -> bool: ...
    def get_dimension(self) -> int: ...
    def get_shape(self) -> int: ...
    def get_point(self) -> npt.NDArray[np.floating]: ...
    def serialize(self) -> npt.NDArray[np.floating]: ...
    def unserialize(self, serialized: npt.NDArray[np.floating]) -> None: ...
    def get_matrix(self) -> npt.NDArray[np.floating]: ...
    @overload
    def __call__(self, index1: int, index2: int) -> float: ...
    def to_eulerangles_body123(self) -> list[float]: ...
    def to_eulerangles_body231(self) -> list[float]: ...
    def to_eulerangles_body312(self) -> list[float]: ...
    def to_eulerangles_body132(self) -> list[float]: ...
    def to_eulerangles_body213(self) -> list[float]: ...
    def to_eulerangles_body321(self) -> list[float]: ...
    def to_eulerangles_body121(self) -> list[float]: ...
    def to_eulerangles_body131(self) -> list[float]: ...
    def to_eulerangles_body212(self) -> list[float]: ...
    def to_eulerangles_body232(self) -> list[float]: ...
    def to_eulerangles_body313(self) -> list[float]: ...
    def to_eulerangles_body323(self) -> list[float]: ...
    def to_eulerangles_space123(self) -> list[float]: ...
    def to_eulerangles_space231(self) -> list[float]: ...
    def to_eulerangles_space312(self) -> list[float]: ...
    def to_eulerangles_space132(self) -> list[float]: ...
    def to_eulerangles_space213(self) -> list[float]: ...
    def to_eulerangles_space321(self) -> list[float]: ...
    def to_eulerangles_space121(self) -> list[float]: ...
    def to_eulerangles_space131(self) -> list[float]: ...
    def to_eulerangles_space212(self) -> list[float]: ...
    def to_eulerangles_space232(self) -> list[float]: ...
    def to_eulerangles_space313(self) -> list[float]: ...
    def to_eulerangles_space323(self) -> list[float]: ...
    def to_quaternion(self) -> list[float]: ...
    def to_gibbs(self) -> list[float]: ...
    def inverse(self) -> SO: ...
    def project_onto_tangent_space(self, vector: npt.NDArray[np.floating] | list[float]) -> npt.NDArray[np.floating]: ...
