from typing import overload, TYPE_CHECKING

if TYPE_CHECKING:
    import numpy.typing as npt
    import numpy as np

class SU:
    point: npt.NDArray[np.complexfloating]

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, matrix: npt.NDArray[np.complexfloating]) -> None: ...
    @staticmethod
    def identity(shape: int) -> SU: ...
    # @staticmethod
    # def project(matrix: npt.NDArray[np.complexfloating]) -> SU: ...
    @overload
    def __init__(self, n: int) -> None: ...
    def to_string(self) -> str: ...
    def get_size(self) -> int: ...
    def is_abelian(self) -> bool: ...
    def get_dimension(self) -> int: ...
    def get_shape(self) -> int: ...
    def get_point(self) -> npt.NDArray[np.complexfloating]: ...
    def serialize(self) -> npt.NDArray[np.floating]: ...
    def unserialize(self, vector: npt.NDArray[np.floating]) -> None: ...
    def get_matrix(self) -> npt.NDArray[np.complexfloating]: ...
    @overload
    def __call__(self, index1: int, index2: int) -> complex: ...
    def inverse(self) -> SU: ...
