from typing import overload, TYPE_CHECKING, List

if TYPE_CHECKING:
    import numpy.typing as npt
    import numpy as np

def concatenate(vectors: List[npt.NDArray[np.floating]]) -> npt.NDArray[np.floating]: ...

@overload
def arange(start: int, stop: int) -> npt.NDArray[np.int32]: ...
@overload
def arange(start: float, stop: float) -> npt.NDArray[np.floating]: ...
@overload
def arange(stop: int) -> npt.NDArray[np.int32]: ...
@overload
def arange(stop: float) -> npt.NDArray[np.floating]: ...

@overload
def repeat(vector: npt.NDArray[np.int32], n: int) -> npt.NDArray[np.int32]: ...
@overload
def repeat(vector: npt.NDArray[np.floating], n: int) -> npt.NDArray[np.floating]: ...

@overload
def tile(vector: npt.NDArray[np.int32], n: int) -> npt.NDArray[np.int32]: ...
@overload
def tile(vector: npt.NDArray[np.floating], n: int) -> npt.NDArray[np.floating]: ...

def linspace(start: float, stop: float, size: int) -> npt.NDArray[np.floating]: ...
def logspace(start: float, stop: float, size: int) -> npt.NDArray[np.floating]: ...

@overload
def column_stack(vectors: List[npt.NDArray[np.int32]]) -> npt.NDArray[np.int32]: ...
@overload
def column_stack(vectors: List[npt.NDArray[np.floating]]) -> npt.NDArray[np.floating]: ...

def horizontal_stack(matrices: List[npt.NDArray[np.floating]]) -> npt.NDArray[np.floating]: ...
def vertical_stack(matrices: List[npt.NDArray[np.floating]]) -> npt.NDArray[np.floating]: ...

def linear_interpolate(x_interp: npt.NDArray[np.floating], x: npt.NDArray[np.floating], y: npt.NDArray[np.floating]) -> npt.NDArray[np.floating]: ...

