from typing import overload, TYPE_CHECKING

if TYPE_CHECKING:
    from lielab.domain import *
    import numpy.typing as npt
    import numpy as np

class CompositeAlgebra:
    point: list[cn | glc | glr | rn | se | so | sp | su]

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, matrix: npt.NDArray[np.complexfloating]) -> None: ...
    @staticmethod
    def basis(index: int, shape: int) -> CompositeAlgebra: ...
    @staticmethod
    def zero(shape: int) -> CompositeAlgebra: ...
    # @staticmethod
    # def from_vector(vector: npt.NDArray[np.floating]) -> CompositeAlgebra: ...
    @staticmethod
    def project(vector: npt.NDArray[np.complexfloating]) -> CompositeAlgebra: ...
    @overload
    def __init__(self, n: int) -> None: ...
    @overload
    def __init__(self, lie_algebras: list[cn | glc | glr | rn | se | so | sp | su]) -> None: ...
    def to_string(self) -> str: ...
    def get_dimension(self) -> int: ...
    def get_size(self) -> int: ...
    def is_abelian(self) -> bool: ...
    def get_shape(self) -> int: ...
    def get_dimensions(self) -> list[int]: ...
    def get_sizes(self) -> list[int]: ...
    def get_shapes(self) -> list[int]: ...
    def get_point(self) -> list[cn | glc | glr | rn | se | so | sp | su]: ...
    def serialize(self) -> npt.NDArray[np.floating]: ...
    def unserialize(self, serialized: npt.NDArray[np.floating]) -> None: ...
    def get_matrix(self) -> npt.NDArray[np.complexfloating]: ...
    def get_vector(self) -> npt.NDArray[np.floating]: ...
    def set_vector(self, vector: npt.NDArray[np.floating]) -> None: ...
    @overload
    def __call__(self, index: int) -> float: ...
    @overload
    def __call__(self, index1: int, index2: int) -> float: ...
    def get_vectors(self) -> list[npt.NDArray[np.floating]]: ...
