from typing import overload, TYPE_CHECKING

if TYPE_CHECKING:
    import numpy.typing as npt
    import numpy as np

class so:
    point: npt.NDArray[np.floating]

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, matrix: npt.NDArray[np.floating]) -> None: ...
    @staticmethod
    def basis(index: int, shape: int) -> so: ...
    @staticmethod
    def zero(shape: int) -> so: ...
    @staticmethod
    def from_vector(vector: npt.NDArray[np.floating]) -> so: ...
    @staticmethod
    def project(matrix: npt.NDArray[np.floating]) -> so: ...
    @overload
    def __init__(self, n: int) -> None: ...
    def to_string(self) -> str: ...
    def get_dimension(self) -> int: ...
    def get_size(self) -> int: ...
    def is_abelian(self) -> bool: ...
    def get_shape(self) -> int: ...
    def get_point(self) -> npt.NDArray[np.floating]: ...
    def serialize(self) -> npt.NDArray[np.floating]: ...
    def unserialize(self, serialized: npt.NDArray[np.floating]) -> None: ...
    def get_matrix(self) -> npt.NDArray[np.floating]: ...
    def get_vector(self) -> npt.NDArray[np.floating]: ...
    def set_vector(self, vector: npt.NDArray[np.floating]) -> None: ...
    @overload
    def __call__(self, index: int) -> float: ...
    @overload
    def __call__(self, index1: int, index2: int) -> float: ...
