from typing import overload, TYPE_CHECKING, List

if TYPE_CHECKING:
    from lielab.domain import *
    import numpy.typing as npt
    import numpy as np

class CompositeManifold:
    point: list[cn | glc | glr | rn | se | so | sp | su |
                CN | GLC | GLR | RN | SE | SO | SP | SU |
                Grassmannian]

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, n: int) -> None: ...
    @overload
    def __init__(self, manifolds: list[cn | glc | glr | rn | se | so | sp | su |
                                       CN | GLC | GLR | RN | SE | SO | SP | SU |
                                       Grassmannian]) -> None: ...
    def to_string(self) -> str: ...
    def get_dimension(self) -> int: ...
    def get_size(self) -> int: ...
    # TODO: iter??
    def get_dimensions(self) -> List[int]: ...
    def get_sizes(self) -> List[int]: ...

    def get_point(self) -> list[cn | glc | glr | rn | se | so | sp | su |
                                CN | GLC | GLR | RN | SE | SO | SP | SU |
                                Grassmannian]: ...
    def serialize(self) -> npt.NDArray[np.floating]: ...
    def unserialize(self, vector: npt.NDArray[np.floating]) -> None: ...
    # TODO: getitem and setitem?
