from typing import overload, TYPE_CHECKING

if TYPE_CHECKING:
    import numpy.typing as npt
    import numpy as np

class Grassmannian:
    point: npt.NDArray[np.floating]

    axes: npt.NDArray[np.floating]
    point_projector: npt.NDArray[np.floating]

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, k: int, n: int) -> None: ...
    @overload
    def __init__(self, point: npt.NDArray[np.floating] | list[float],
                       axes: npt.NDArray[np.floating]) -> None: ...
    @staticmethod
    def project(point: npt.NDArray[np.floating] | list[float],
                axes: npt.NDArray[np.floating] | list[float]) -> Grassmannian: ...
    def to_string(self) -> str: ...
    def get_dimension(self) -> int: ...
    def get_size(self) -> int: ...
    def get_point(self) -> npt.NDArray[np.floating]: ...
    def serialize(self) -> npt.NDArray[np.floating]: ...
    def unserialize(self, vector: npt.NDArray[np.floating] | list[float]) -> None: ...
    # def getitem, setitem, etc...
    def project_point(self, point: npt.NDArray[np.floating] | list[float]) -> npt.NDArray[np.floating]: ...
    def project_vector_onto_tangent_space(self, vector: npt.NDArray[np.floating] | list[float]) -> npt.NDArray[np.floating]: ...
    def project_vector_onto_normal_space(self, vector: npt.NDArray[np.floating] | list[float]) -> npt.NDArray[np.floating]: ...
    def axes_intersection(self, point: npt.NDArray[np.floating] | list[float],
                                other_axes: npt.NDArray[np.floating]) -> npt.NDArray[np.floating]: ...
    
