#include "operators/addition/addition_cn.hpp"
#include "operators/addition/addition_gl.hpp"
#include "operators/addition/addition_glc.hpp"
#include "operators/addition/addition_rn.hpp"
#include "operators/addition/addition_se.hpp"
#include "operators/addition/addition_so.hpp"
#include "operators/addition/addition_sp.hpp"
#include "operators/addition/addition_su.hpp"

#include "operators/product/alg_alg_prod_cn.hpp"
#include "operators/product/alg_alg_prod_gl.hpp"
#include "operators/product/alg_alg_prod_glc.hpp"
#include "operators/product/alg_alg_prod_rn.hpp"
#include "operators/product/alg_alg_prod_so.hpp"
#include "operators/product/alg_alg_prod_se.hpp"
#include "operators/product/alg_alg_prod_sp.hpp"
#include "operators/product/alg_alg_prod_su.hpp"

#include "operators/product/alg_grp_prod_cn.hpp"
#include "operators/product/alg_grp_prod_gl.hpp"
#include "operators/product/alg_grp_prod_glc.hpp"
#include "operators/product/alg_grp_prod_rn.hpp"
#include "operators/product/alg_grp_prod_se.hpp"
#include "operators/product/alg_grp_prod_so.hpp"
#include "operators/product/alg_grp_prod_sp.hpp"
#include "operators/product/alg_grp_prod_su.hpp"

#include "operators/product/grp_alg_prod_CN.hpp"
#include "operators/product/grp_alg_prod_GL.hpp"
#include "operators/product/grp_alg_prod_GLC.hpp"
#include "operators/product/grp_alg_prod_RN.hpp"
#include "operators/product/grp_alg_prod_SE.hpp"
#include "operators/product/grp_alg_prod_SO.hpp"
#include "operators/product/grp_alg_prod_SP.hpp"
#include "operators/product/grp_alg_prod_SU.hpp"

#include "operators/subtraction/subtraction_cn.hpp"
#include "operators/subtraction/subtraction_gl.hpp"
#include "operators/subtraction/subtraction_glc.hpp"
#include "operators/subtraction/subtraction_rn.hpp"
#include "operators/subtraction/subtraction_se.hpp"
#include "operators/subtraction/subtraction_so.hpp"
#include "operators/subtraction/subtraction_sp.hpp"
#include "operators/subtraction/subtraction_su.hpp"
