#include <Lielab.hpp>
#include <string>
#include <Eigen/Core>
#include <pybind11/pybind11.h>
#include <pybind11/operators.h>
#include <pybind11/functional.h>
#include <pybind11/complex.h>
#include <pybind11/eigen.h>
#include <pybind11/numpy.h>
#include <pybind11/stl.h>

#include "pyfunctions.hpp"

namespace py = pybind11;

std::string matstr(const Eigen::VectorXd& mat);
std::string matstr(const Eigen::VectorXcd& mat);
std::string matstr(const Eigen::MatrixXd& mat);
std::string matstr(const Eigen::MatrixXcd& mat);

void bind_functions(py::module& m_functions)
{
    using namespace Lielab::domain;

    m_functions.def("left_Lie_group_action", &Lielab::functions::left_Lie_group_action, "Default action by left product.");
    m_functions.def("right_Lie_group_action", &Lielab::functions::right_Lie_group_action, "Action by right product.");
    m_functions.def("left_Lie_algebra_action", &Lielab::functions::left_Lie_algebra_action, "Default daction by left product.");
    m_functions.def("right_Lie_algebra_action", &Lielab::functions::right_Lie_algebra_action, "dAction by right product.");
    // m_functions.def("copair", &Lielab::functions::copair<glr>, "The copair function.");
    // m_functions.def("copair", &Lielab::functions::copair<rn>, "The copair function.");
    // m_functions.def("copair", &Lielab::functions::copair<so>, "The copair function.");
    // m_functions.def("copair", &Lielab::functions::copair<sp>, "The copair function.");
    // m_functions.def("copair", &Lielab::functions::copair<su>, "The copair function.");
    m_functions.def("Ad_numerical", [](const cn& a){return Lielab::functions::Ad_numerical(a);}, py::arg("a"), "The numerical Ad function.");
    m_functions.def("Ad_numerical", [](const glr& a){return Lielab::functions::Ad_numerical(a);}, py::arg("a"), "The numerical Ad function.");
    m_functions.def("Ad_numerical", [](const glc& a){return Lielab::functions::Ad_numerical(a);}, py::arg("a"), "The numerical Ad function.");
    m_functions.def("Ad_numerical", [](const rn& a){return Lielab::functions::Ad_numerical(a);}, py::arg("a"), "The numerical Ad function.");
    m_functions.def("Ad_numerical", [](const se& a){return Lielab::functions::Ad_numerical(a);}, py::arg("a"), "The numerical Ad function.");
    m_functions.def("Ad_numerical", [](const so& a){return Lielab::functions::Ad_numerical(a);}, py::arg("a"), "The numerical Ad function.");
    m_functions.def("Ad_numerical", [](const sp& a){return Lielab::functions::Ad_numerical(a);}, py::arg("a"), "The numerical Ad function.");
    m_functions.def("Ad_numerical", [](const su& a){return Lielab::functions::Ad_numerical(a);}, py::arg("a"), "The numerical Ad function.");
    m_functions.def("Ad", [](const cn& a){return Lielab::functions::Ad(a);}, py::arg("a"), "The Ad function.");
    m_functions.def("Ad", [](const glr& a){return Lielab::functions::Ad(a);}, py::arg("a"), "The Ad function.");
    m_functions.def("Ad", [](const glc& a){return Lielab::functions::Ad(a);}, py::arg("a"), "The Ad function.");
    m_functions.def("Ad", [](const rn& a){return Lielab::functions::Ad(a);}, py::arg("a"), "The Ad function.");
    m_functions.def("Ad", [](const se& a){return Lielab::functions::Ad(a);}, py::arg("a"), "The Ad function.");
    m_functions.def("Ad", [](const so& a){return Lielab::functions::Ad(a);}, py::arg("a"), "The Ad function.");
    m_functions.def("Ad", [](const sp& a){return Lielab::functions::Ad(a);}, py::arg("a"), "The Ad function.");
    m_functions.def("Ad", [](const su& a){return Lielab::functions::Ad(a);}, py::arg("a"), "The Ad function.");
    m_functions.def("Ad", [](const cn& a, cn& b){return Lielab::functions::Ad(a, b);}, py::arg("a"), py::arg("b"), "The Ad function.");
    m_functions.def("Ad", [](const glr& a, glr& b){return Lielab::functions::Ad(a, b);}, py::arg("a"), py::arg("b"), "The Ad function.");
    m_functions.def("Ad", [](const glc& a, glc& b){return Lielab::functions::Ad(a, b);}, py::arg("a"), py::arg("b"), "The Ad function.");
    m_functions.def("Ad", [](const rn& a, rn& b){return Lielab::functions::Ad(a, b);}, py::arg("a"), py::arg("b"), "The Ad function.");
    m_functions.def("Ad", [](const se& a, se& b){return Lielab::functions::Ad(a, b);}, py::arg("a"), py::arg("b"), "The Ad function.");
    m_functions.def("Ad", [](const so& a, so& b){return Lielab::functions::Ad(a, b);}, py::arg("a"), py::arg("b"), "The Ad function.");
    m_functions.def("Ad", [](const sp& a, sp& b){return Lielab::functions::Ad(a, b);}, py::arg("a"), py::arg("b"), "The Ad function.");
    m_functions.def("Ad", [](const su& a, su& b){return Lielab::functions::Ad(a, b);}, py::arg("a"), py::arg("b"), "The Ad function.");
    m_functions.def("Ad", [](const CN& A, cn& b){return Lielab::functions::Ad(A, b);}, py::arg("A"), py::arg("b"), "The Ad function.");
    m_functions.def("Ad", [](const GLR& A, glr& b){return Lielab::functions::Ad(A, b);}, py::arg("A"), py::arg("b"), "The Ad function.");
    m_functions.def("Ad", [](const GLC& A, glc& b){return Lielab::functions::Ad(A, b);}, py::arg("A"), py::arg("b"), "The Ad function.");
    m_functions.def("Ad", [](const RN& A, rn& b){return Lielab::functions::Ad(A, b);}, py::arg("A"), py::arg("b"), "The Ad function.");
    m_functions.def("Ad", [](const SE& A, se& b){return Lielab::functions::Ad(A, b);}, py::arg("A"), py::arg("b"), "The Ad function.");
    m_functions.def("Ad", [](const SO& A, so& b){return Lielab::functions::Ad(A, b);}, py::arg("A"), py::arg("b"), "The Ad function.");
    m_functions.def("Ad", [](const SP& A, sp& b){return Lielab::functions::Ad(A, b);}, py::arg("A"), py::arg("b"), "The Ad function.");
    m_functions.def("Ad", [](const SU& A, su& b){return Lielab::functions::Ad(A, b);}, py::arg("A"), py::arg("b"), "The Ad function.");
    m_functions.def("Ad", [](const CompositeGroup A, const CompositeAlgebra& b){return Lielab::functions::Ad(A, b);}, "The Ad function.", py::arg("A"), py::arg("b"));
    // m_functions.def("Cayley", &Lielab::functions::Cayley<cn>, "The Cayley function.");
    // m_functions.def("Cayley", &Lielab::functions::Cayley<glr>, "The Cayley function.");
    // m_functions.def("Cayley", &Lielab::functions::Cayley<glc>, "The Cayley function.");
    m_functions.def("Cayley", &Lielab::functions::Cayley<rn>, "The Cayley function.");
    // m_functions.def("Cayley", &Lielab::functions::Cayley<se>, "The Cayley function.");
    m_functions.def("Cayley", &Lielab::functions::Cayley<so>, "The Cayley function.");
    m_functions.def("Cayley", &Lielab::functions::Cayley<sp>, "The Cayley function.");
    m_functions.def("Cayley", &Lielab::functions::Cayley<su>, "The Cayley function.");
    m_functions.def("Cayley", [](CompositeAlgebra a){return Lielab::functions::Cayley(a);}, py::arg("a"), "The Cayley function.");
    // m_functions.def("Cayley2", &Lielab::functions::Cayley2<cn>, "The Cayley2 function.");
    // m_functions.def("Cayley2", &Lielab::functions::Cayley2<glr>, "The Cayley2 function.");
    // m_functions.def("Cayley2", &Lielab::functions::Cayley2<glc>, "The Cayley2 function.");
    m_functions.def("Cayley2", &Lielab::functions::Cayley2<rn>, "The Cayley2 function.");
    // m_functions.def("Cayley2", &Lielab::functions::Cayley2<se>, "The Cayley2 function.");
    m_functions.def("Cayley2", &Lielab::functions::Cayley2<so>, "The Cayley2 function.");
    m_functions.def("Cayley2", &Lielab::functions::Cayley2<sp>, "The Cayley2 function.");
    // m_functions.def("Cayley2", &Lielab::functions::Cayley2<su>, "The Cayley2 function.");
    m_functions.def("commutator", &Lielab::functions::commutator<cn>, "The commutator function.");
    m_functions.def("commutator", &Lielab::functions::commutator<glr>, "The commutator function.");
    m_functions.def("commutator", &Lielab::functions::commutator<glc>, "The commutator function.");
    m_functions.def("commutator", &Lielab::functions::commutator<rn>, "The commutator function.");
    m_functions.def("commutator", &Lielab::functions::commutator<se>, "The commutator function.");
    m_functions.def("commutator", &Lielab::functions::commutator<so>, "The commutator function.");
    m_functions.def("commutator", &Lielab::functions::commutator<sp>, "The commutator function.");
    m_functions.def("commutator", &Lielab::functions::commutator<su>, "The commutator function.");
    m_functions.def("commutator", &Lielab::functions::commutator<CompositeAlgebra>, "The commutator function.");
    // m_functions.def("Killing", &Lielab::functions::Killing<cn>, "The Killing function.");
    // m_functions.def("Killing", &Lielab::functions::Killing<glr>, "The Killing function.");
    // m_functions.def("Killing", &Lielab::functions::Killing<glc>, "The Killing function.");
    m_functions.def("Killing", &Lielab::functions::Killing<rn>, "The Killing function.");
    // m_functions.def("Killing", &Lielab::functions::Killing<se>, "The Killing function.");
    m_functions.def("Killing", &Lielab::functions::Killing<so>, "The Killing function.");
    m_functions.def("Killing", &Lielab::functions::Killing<sp>, "The Killing function.");
    m_functions.def("Killing", &Lielab::functions::Killing<su>, "The Killing function."); // TODO: Might be wrong
    m_functions.def("Killingform", &Lielab::functions::Killingform<cn>, "The Killingform function.");
    m_functions.def("Killingform", &Lielab::functions::Killingform<glr>, "The Killingform function.");
    m_functions.def("Killingform", &Lielab::functions::Killingform<glc>, "The Killingform function.");
    // m_functions.def("Killingform", &Lielab::functions::Killingform<se>, "The Killingform function.");
    m_functions.def("Killingform", &Lielab::functions::Killingform<rn>, "The Killingform function.");
    m_functions.def("Killingform", &Lielab::functions::Killingform<so>, "The Killingform function.");
    m_functions.def("Killingform", &Lielab::functions::Killingform<sp>, "The Killingform function.");
    m_functions.def("Killingform", &Lielab::functions::Killingform<su>, "The Killingform function."); // TODO: Might be wrong
    m_functions.def("ad_numerical", [](const cn& a, const int p){return Lielab::functions::ad_numerical(a, p);}, py::arg("a"), py::arg("p") = 1, "The numerical ad function.");
    m_functions.def("ad_numerical", [](const cn& a, const cn& b, const int p){return Lielab::functions::ad_numerical(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The numerical ad function.");
    m_functions.def("ad_numerical", [](const glr& a, const int p){return Lielab::functions::ad_numerical(a, p);}, py::arg("a"), py::arg("p") = 1, "The numerical ad function.");
    m_functions.def("ad_numerical", [](const glr& a, const glr& b, const int p){return Lielab::functions::ad_numerical(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The numerical ad function.");
    m_functions.def("ad_numerical", [](const glc& a, const int p){return Lielab::functions::ad_numerical(a, p);}, py::arg("a"), py::arg("p") = 1, "The numerical ad function.");
    m_functions.def("ad_numerical", [](const glc& a, const glc& b, const int p){return Lielab::functions::ad_numerical(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The numerical ad function.");
    m_functions.def("ad_numerical", [](const rn& a, const int p){return Lielab::functions::ad_numerical(a, p);}, py::arg("a"), py::arg("p") = 1, "The numerical ad function.");
    m_functions.def("ad_numerical", [](const rn& a, const rn& b, const int p){return Lielab::functions::ad_numerical(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The numerical ad function.");
    m_functions.def("ad_numerical", [](const se& a, const int p){return Lielab::functions::ad_numerical(a, p);}, py::arg("a"), py::arg("p") = 1, "The numerical ad function.");
    m_functions.def("ad_numerical", [](const se& a, const se& b, const int p){return Lielab::functions::ad_numerical(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The numerical ad function.");
    m_functions.def("ad_numerical", [](const so& a, const int p){return Lielab::functions::ad_numerical(a, p);}, py::arg("a"), py::arg("p") = 1, "The numerical ad function.");
    m_functions.def("ad_numerical", [](const so& a, const so& b, const int p){return Lielab::functions::ad_numerical(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The numerical ad function.");
    m_functions.def("ad_numerical", [](const sp& a, const int p){return Lielab::functions::ad_numerical(a, p);}, py::arg("a"), py::arg("p") = 1, "The numerical ad function.");
    m_functions.def("ad_numerical", [](const sp& a, const sp& b, const int p){return Lielab::functions::ad_numerical(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The numerical ad function.");
    m_functions.def("ad_numerical", [](const su& a, const int p){return Lielab::functions::ad_numerical(a, p);}, py::arg("a"), py::arg("p") = 1, "The numerical ad function.");
    m_functions.def("ad_numerical", [](const su& a, const su& b, const int p){return Lielab::functions::ad_numerical(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The numerical ad function.");
    m_functions.def("ad", [](const cn& a, const int p){return Lielab::functions::ad(a, p);}, py::arg("a"), py::arg("p") = 1, "The ad function.");
    m_functions.def("ad", [](const cn& a, const cn& b, const int p){return Lielab::functions::ad(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The ad function.");
    m_functions.def("ad", [](const glr& a, const int p){return Lielab::functions::ad(a, p);}, py::arg("a"), py::arg("p") = 1, "The ad function.");
    m_functions.def("ad", [](const glr& a, const glr& b, const int p){return Lielab::functions::ad(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The ad function.");
    m_functions.def("ad", [](const glc& a, const int p){return Lielab::functions::ad(a, p);}, py::arg("a"), py::arg("p") = 1, "The ad function.");
    m_functions.def("ad", [](const glc& a, const glc& b, const int p){return Lielab::functions::ad(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The ad function.");
    m_functions.def("ad", [](const rn& a, const int p){return Lielab::functions::ad(a, p);}, py::arg("a"), py::arg("p") = 1, "The ad function.");
    m_functions.def("ad", [](const rn& a, const rn& b, const int p){return Lielab::functions::ad(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The ad function.");
    m_functions.def("ad", [](const se& a, const int p){return Lielab::functions::ad(a, p);}, py::arg("a"), py::arg("p") = 1, "The ad function.");
    m_functions.def("ad", [](const se& a, const se& b, const int p){return Lielab::functions::ad(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The ad function.");
    m_functions.def("ad", [](const so& a, const int p){return Lielab::functions::ad(a, p);}, py::arg("a"), py::arg("p") = 1, "The ad function.");
    m_functions.def("ad", [](const so& a, const so& b, const int p){return Lielab::functions::ad(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The ad function.");
    m_functions.def("ad", [](const sp& a, const int p){return Lielab::functions::ad(a, p);}, py::arg("a"), py::arg("p") = 1, "The ad function.");
    m_functions.def("ad", [](const sp& a, const sp& b, const int p){return Lielab::functions::ad(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The ad function.");
    m_functions.def("ad", [](const su& a, const int p){return Lielab::functions::ad(a, p);}, py::arg("a"), py::arg("p") = 1, "The ad function.");
    m_functions.def("ad", [](const su& a, const su& b, const int p){return Lielab::functions::ad(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The ad function.");
    m_functions.def("ad", [](const CompositeAlgebra& a, const int p){return Lielab::functions::ad(a, p);}, py::arg("a"), py::arg("p") = 1, "The ad function.");
    m_functions.def("ad", [](const CompositeAlgebra& a, const CompositeAlgebra& b, const int p){return Lielab::functions::ad(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The ad function.");
    m_functions.def("coad_numerical", [](const cn& a, const int p){return Lielab::functions::coad_numerical(a, p);}, py::arg("a"), py::arg("p") = 1, "The numerical coad function.");
    m_functions.def("coad_numerical", [](const cn& a, const cn& b, const int p){return Lielab::functions::coad_numerical(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The numerical coad function.");
    m_functions.def("coad_numerical", [](const glr& a, const int p){return Lielab::functions::coad_numerical(a, p);}, py::arg("a"), py::arg("p") = 1, "The numerical coad function.");
    m_functions.def("coad_numerical", [](const glr& a, const glr& b, const int p){return Lielab::functions::coad_numerical(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The numerical coad function.");
    m_functions.def("coad_numerical", [](const glc& a, const int p){return Lielab::functions::coad_numerical(a, p);}, py::arg("a"), py::arg("p") = 1, "The numerical coad function.");
    m_functions.def("coad_numerical", [](const glc& a, const glc& b, const int p){return Lielab::functions::coad_numerical(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The numerical coad function.");
    m_functions.def("coad_numerical", [](const rn& a, const int p){return Lielab::functions::coad_numerical(a, p);}, py::arg("a"), py::arg("p") = 1, "The numerical coad function.");
    m_functions.def("coad_numerical", [](const rn& a, const rn& b, const int p){return Lielab::functions::coad_numerical(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The numerical coad function.");
    m_functions.def("coad_numerical", [](const se& a, const int p){return Lielab::functions::coad_numerical(a, p);}, py::arg("a"), py::arg("p") = 1, "The numerical coad function.");
    m_functions.def("coad_numerical", [](const se& a, const se& b, const int p){return Lielab::functions::coad_numerical(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The numerical coad function.");
    m_functions.def("coad_numerical", [](const so& a, const int p){return Lielab::functions::coad_numerical(a, p);}, py::arg("a"), py::arg("p") = 1, "The numerical coad function.");
    m_functions.def("coad_numerical", [](const so& a, const so& b, const int p){return Lielab::functions::coad_numerical(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The numerical coad function.");
    m_functions.def("coad_numerical", [](const sp& a, const int p){return Lielab::functions::coad_numerical(a, p);}, py::arg("a"), py::arg("p") = 1, "The numerical coad function.");
    m_functions.def("coad_numerical", [](const sp& a, const sp& b, const int p){return Lielab::functions::coad_numerical(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The numerical coad function.");
    m_functions.def("coad_numerical", [](const su& a, const int p){return Lielab::functions::coad_numerical(a, p);}, py::arg("a"), py::arg("p") = 1, "The numerical coad function.");
    m_functions.def("coad_numerical", [](const su& a, const su& b, const int p){return Lielab::functions::coad_numerical(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The numerical coad function.");
    m_functions.def("coad", [](const cn& a, const int p){return Lielab::functions::coad(a, p);}, py::arg("a"), py::arg("p") = 1, "The coad function.");
    m_functions.def("coad", [](const cn& a, const cn& b, const int p){return Lielab::functions::coad(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The coad function.");
    m_functions.def("coad", [](const glr& a, const int p){return Lielab::functions::coad(a, p);}, py::arg("a"), py::arg("p") = 1, "The coad function.");
    m_functions.def("coad", [](const glr& a, const glr& b, const int p){return Lielab::functions::coad(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The coad function.");
    m_functions.def("coad", [](const glc& a, const int p){return Lielab::functions::coad(a, p);}, py::arg("a"), py::arg("p") = 1, "The coad function.");
    m_functions.def("coad", [](const glc& a, const glc& b, const int p){return Lielab::functions::coad(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The coad function.");
    m_functions.def("coad", [](const rn& a, const int p){return Lielab::functions::coad(a, p);}, py::arg("a"), py::arg("p") = 1, "The coad function.");
    m_functions.def("coad", [](const rn& a, const rn& b, const int p){return Lielab::functions::coad(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The coad function.");
    m_functions.def("coad", [](const se& a, const int p){return Lielab::functions::coad(a, p);}, py::arg("a"), py::arg("p") = 1, "The coad function.");
    m_functions.def("coad", [](const se& a, const se& b, const int p){return Lielab::functions::coad(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The coad function.");
    m_functions.def("coad", [](const so& a, const int p){return Lielab::functions::coad(a, p);}, py::arg("a"), py::arg("p") = 1, "The coad function.");
    m_functions.def("coad", [](const so& a, const so& b, const int p){return Lielab::functions::coad(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The coad function.");
    m_functions.def("coad", [](const sp& a, const int p){return Lielab::functions::coad(a, p);}, py::arg("a"), py::arg("p") = 1, "The coad function.");
    m_functions.def("coad", [](const sp& a, const sp& b, const int p){return Lielab::functions::coad(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The coad function.");
    m_functions.def("coad", [](const su& a, const int p){return Lielab::functions::coad(a, p);}, py::arg("a"), py::arg("p") = 1, "The coad function.");
    m_functions.def("coad", [](const su& a, const su& b, const int p){return Lielab::functions::coad(a, b, p);}, py::arg("a"), py::arg("b"), py::arg("p") = 1, "The coad function.");
    m_functions.def("exp_numerical", &Lielab::functions::exp_numerical<cn>, "The numerical exponential function.");
    m_functions.def("exp_numerical", &Lielab::functions::exp_numerical<glr>, "The numerical exponential function.");
    m_functions.def("exp_numerical", &Lielab::functions::exp_numerical<glc>, "The numerical exponential function.");
    m_functions.def("exp_numerical", &Lielab::functions::exp_numerical<rn>, "The numerical exponential function.");
    m_functions.def("exp_numerical", &Lielab::functions::exp_numerical<se>, "The numerical exponential function.");
    m_functions.def("exp_numerical", &Lielab::functions::exp_numerical<so>, "The numerical exponential function.");
    m_functions.def("exp_numerical", &Lielab::functions::exp_numerical<sp>, "The numerical exponential function.");
    m_functions.def("exp_numerical", &Lielab::functions::exp_numerical<su>, "The numerical exponential function.");
    m_functions.def("exp", &Lielab::functions::exp<cn>, "The exponential function.");
    m_functions.def("exp", &Lielab::functions::exp<glr>, "The exponential function.");
    m_functions.def("exp", &Lielab::functions::exp<glc>, "The exponential function.");
    m_functions.def("exp", &Lielab::functions::exp<rn>, "The exponential function.");
    m_functions.def("exp", &Lielab::functions::exp<se>, "The exponential function.");
    m_functions.def("exp", &Lielab::functions::exp<so>, "The exponential function.");
    m_functions.def("exp", &Lielab::functions::exp<sp>, "The exponential function.");
    m_functions.def("exp", &Lielab::functions::exp<su>, "The exponential function.");
    m_functions.def("exp", [](const CompositeAlgebra& a){return Lielab::functions::exp(a);}, "The exponential function.");
    m_functions.def("log_numerical", &Lielab::functions::log_numerical<CN>, "The numerical logarithm function.");
    m_functions.def("log_numerical", &Lielab::functions::log_numerical<GLR>, "The numerical logarithm function.");
    m_functions.def("log_numerical", &Lielab::functions::log_numerical<GLC>, "The numerical logarithm function.");
    m_functions.def("log_numerical", &Lielab::functions::log_numerical<RN>, "The numerical logarithm function.");
    m_functions.def("log_numerical", &Lielab::functions::log_numerical<SE>, "The numerical logarithm function.");
    m_functions.def("log_numerical", &Lielab::functions::log_numerical<SO>, "The numerical logarithm function.");
    m_functions.def("log_numerical", &Lielab::functions::log_numerical<SP>, "The numerical logarithm function.");
    m_functions.def("log_numerical", &Lielab::functions::log_numerical<SU>, "The numerical logarithm function.");
    m_functions.def("log", &Lielab::functions::log<CN>, "The logarithm function.", py::arg("G"));
    m_functions.def("log", &Lielab::functions::log<GLR>, "The logarithm function.", py::arg("G"));
    m_functions.def("log", &Lielab::functions::log<GLC>, "The logarithm function.", py::arg("G"));
    m_functions.def("log", &Lielab::functions::log<RN>, "The logarithm function.", py::arg("G"));
    m_functions.def("log", &Lielab::functions::log<SE>, "The logarithm function.", py::arg("G"));
    m_functions.def("log", &Lielab::functions::log<SO>, "The logarithm function.", py::arg("G"));
    m_functions.def("log", &Lielab::functions::log<SP>, "The logarithm function.", py::arg("G"));
    m_functions.def("log", &Lielab::functions::log<SU>, "The logarithm function.", py::arg("G"));
    m_functions.def("log", [](CompositeGroup A){return Lielab::functions::log(A);}, py::arg("A"), "The logarithm function.");
    // m_functions.def("dCayleyinv", &Lielab::functions::dCayleyinv<cn>, "The dCayleyinv function.");
    m_functions.def("dCayleyinv", &Lielab::functions::dCayleyinv<glr>, "The dCayleyinv function.");
    // m_functions.def("dCayleyinv", &Lielab::functions::dCayleyinv<glc>, "The dCayleyinv function.");
    m_functions.def("dCayleyinv", &Lielab::functions::dCayleyinv<rn>, "The dCayleyinv function.");
    // m_functions.def("dCayleyinv", &Lielab::functions::dCayleyinv<se>, "The dCayleyinv function.");
    m_functions.def("dCayleyinv", &Lielab::functions::dCayleyinv<so>, "The dCayleyinv function.");
    m_functions.def("dCayleyinv", &Lielab::functions::dCayleyinv<sp>, "The dCayleyinv function.");
    m_functions.def("dCayleyinv", &Lielab::functions::dCayleyinv<su>, "The dCayleyinv function.");
    m_functions.def("dCayleyinv", [](const CompositeAlgebra& a, const CompositeAlgebra& b){return Lielab::functions::dCayleyinv(a, b);}, "The dCayleyinv function.");
    m_functions.def("dexp_numerical", [](const cn& a, const size_t order){return Lielab::functions::dexp_numerical(a, order);}, "The numerical dexp function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexp_numerical", [](const cn& a, const cn& b, const size_t order){return Lielab::functions::dexp_numerical(a, b, order);}, "The numerical dexp function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexp_numerical", [](const glr& a, const size_t order){return Lielab::functions::dexp_numerical(a, order);}, "The numerical dexp function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexp_numerical", [](const glr& a, const glr& b, const size_t order){return Lielab::functions::dexp_numerical(a, b, order);}, "The numerical dexp function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexp_numerical", [](const glc& a, const size_t order){return Lielab::functions::dexp_numerical(a, order);}, "The numerical dexp function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexp_numerical", [](const glc& a, const glc& b, const size_t order){return Lielab::functions::dexp_numerical(a, b, order);}, "The numerical dexp function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexp_numerical", [](const rn& a, const size_t order){return Lielab::functions::dexp_numerical(a, order);}, "The numerical dexp function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexp_numerical", [](const rn& a, const rn& b, const size_t order){return Lielab::functions::dexp_numerical(a, b, order);}, "The numerical dexp function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexp_numerical", [](const se& a, const size_t order){return Lielab::functions::dexp_numerical(a, order);}, "The numerical dexp function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexp_numerical", [](const se& a, const se& b, const size_t order){return Lielab::functions::dexp_numerical(a, b, order);}, "The numerical dexp function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexp_numerical", [](const so& a, const size_t order){return Lielab::functions::dexp_numerical(a, order);}, "The numerical dexp function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexp_numerical", [](const so& a, const so& b, const size_t order){return Lielab::functions::dexp_numerical(a, b, order);}, "The numerical dexp function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexp_numerical", [](const sp& a, const size_t order){return Lielab::functions::dexp_numerical(a, order);}, "The numerical dexp function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexp_numerical", [](const sp& a, const sp& b, const size_t order){return Lielab::functions::dexp_numerical(a, b, order);}, "The numerical dexp function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexp_numerical", [](const su& a, const size_t order){return Lielab::functions::dexp_numerical(a, order);}, "The numerical dexp function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexp_numerical", [](const su& a, const su& b, const size_t order){return Lielab::functions::dexp_numerical(a, b, order);}, "The numerical dexp function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexp", [](const cn& a, const size_t order){return Lielab::functions::dexp(a, order);}, "The dexp function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexp", [](const cn& a, const cn& b, const size_t order){return Lielab::functions::dexp(a, b, order);}, "The dexp function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexp", [](const glr& a, const size_t order){return Lielab::functions::dexp(a, order);}, "The dexp function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexp", [](const glr& a, const glr& b, const size_t order){return Lielab::functions::dexp(a, b, order);}, "The dexp function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexp", [](const glc& a, const size_t order){return Lielab::functions::dexp(a, order);}, "The dexp function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexp", [](const glc& a, const glc& b, const size_t order){return Lielab::functions::dexp(a, b, order);}, "The dexp function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexp", [](const rn& a, const size_t order){return Lielab::functions::dexp(a, order);}, "The dexp function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexp", [](const rn& a, const rn& b, const size_t order){return Lielab::functions::dexp(a, b, order);}, "The dexp function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexp", [](const se& a, const size_t order){return Lielab::functions::dexp(a, order);}, "The dexp function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexp", [](const se& a, const se& b, const size_t order){return Lielab::functions::dexp(a, b, order);}, "The dexp function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexp", [](const so& a, const size_t order){return Lielab::functions::dexp(a, order);}, "The dexp function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexp", [](const so& a, const so& b, const size_t order){return Lielab::functions::dexp(a, b, order);}, "The dexp function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexp", [](const sp& a, const size_t order){return Lielab::functions::dexp(a, order);}, "The dexp function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexp", [](const sp& a, const sp& b, const size_t order){return Lielab::functions::dexp(a, b, order);}, "The dexp function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexp", [](const su& a, const size_t order){return Lielab::functions::dexp(a, order);}, "The dexp function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexp", [](const su& a, const su& b, const size_t order){return Lielab::functions::dexp(a, b, order);}, "The dexp function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexp", [](const CompositeAlgebra a, const CompositeAlgebra& b, const size_t order){return Lielab::functions::dexp(a, b, order);}, "The dexp function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexpinv_numerical", [](const cn& a, const size_t order){return Lielab::functions::dexpinv_numerical(a, order);}, "The numerical dexpinv function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexpinv_numerical", [](const cn& a, const cn& b, const size_t order){return Lielab::functions::dexpinv_numerical(a, b, order);}, "The numerical dexpinv function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexpinv_numerical", [](const glr& a, const size_t order){return Lielab::functions::dexpinv_numerical(a, order);}, "The numerical dexpinv function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexpinv_numerical", [](const glr& a, const glr& b, const size_t order){return Lielab::functions::dexpinv_numerical(a, b, order);}, "The numerical dexpinv function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexpinv_numerical", [](const glc& a, const size_t order){return Lielab::functions::dexpinv_numerical(a, order);}, "The numerical dexpinv function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexpinv_numerical", [](const glc& a, const glc& b, const size_t order){return Lielab::functions::dexpinv_numerical(a, b, order);}, "The numerical dexpinv function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexpinv_numerical", [](const rn& a, const size_t order){return Lielab::functions::dexpinv_numerical(a, order);}, "The numerical dexpinv function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexpinv_numerical", [](const rn& a, const rn& b, const size_t order){return Lielab::functions::dexpinv_numerical(a, b, order);}, "The numerical dexpinv function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexpinv_numerical", [](const se& a, const size_t order){return Lielab::functions::dexpinv_numerical(a, order);}, "The numerical dexpinv function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexpinv_numerical", [](const se& a, const se& b, const size_t order){return Lielab::functions::dexpinv_numerical(a, b, order);}, "The numerical dexpinv function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexpinv_numerical", [](const so& a, const size_t order){return Lielab::functions::dexpinv_numerical(a, order);}, "The numerical dexpinv function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexpinv_numerical", [](const so& a, const so& b, const size_t order){return Lielab::functions::dexpinv_numerical(a, b, order);}, "The numerical dexpinv function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexpinv_numerical", [](const sp& a, const size_t order){return Lielab::functions::dexpinv_numerical(a, order);}, "The numerical dexpinv function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexpinv_numerical", [](const sp& a, const sp& b, const size_t order){return Lielab::functions::dexpinv_numerical(a, b, order);}, "The numerical dexpinv function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexpinv_numerical", [](const su& a, const size_t order){return Lielab::functions::dexpinv_numerical(a, order);}, "The numerical dexpinv function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexpinv_numerical", [](const su& a, const su& b, const size_t order){return Lielab::functions::dexpinv_numerical(a, b, order);}, "The numerical dexpinv function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexpinv", [](const cn& a, const size_t order){return Lielab::functions::dexpinv(a, order);}, "The dexpinv function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexpinv", [](const cn& a, const cn& b, const size_t order){return Lielab::functions::dexpinv(a, b, order);}, "The dexpinv function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexpinv", [](const glr& a, const size_t order){return Lielab::functions::dexpinv(a, order);}, "The dexpinv function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexpinv", [](const glr& a, const glr& b, const size_t order){return Lielab::functions::dexpinv(a, b, order);}, "The dexpinv function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexpinv", [](const glc& a, const size_t order){return Lielab::functions::dexpinv(a, order);}, "The dexpinv function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexpinv", [](const glc& a, const glc& b, const size_t order){return Lielab::functions::dexpinv(a, b, order);}, "The dexpinv function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexpinv", [](const rn& a, const size_t order){return Lielab::functions::dexpinv(a, order);}, "The dexpinv function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexpinv", [](const rn& a, const rn& b, const size_t order){return Lielab::functions::dexpinv(a, b, order);}, "The dexpinv function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexpinv", [](const se& a, const size_t order){return Lielab::functions::dexpinv(a, order);}, "The dexpinv function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexpinv", [](const se& a, const se& b, const size_t order){return Lielab::functions::dexpinv(a, b, order);}, "The dexpinv function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexpinv", [](const so& a, const size_t order){return Lielab::functions::dexpinv(a, order);}, "The dexpinv function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexpinv", [](const so& a, const so& b, const size_t order){return Lielab::functions::dexpinv(a, b, order);}, "The dexpinv function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexpinv", [](const sp& a, const size_t order){return Lielab::functions::dexpinv(a, order);}, "The dexpinv function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexpinv", [](const sp& a, const sp& b, const size_t order){return Lielab::functions::dexpinv(a, b, order);}, "The dexpinv function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexpinv", [](const su& a, const size_t order){return Lielab::functions::dexpinv(a, order);}, "The dexpinv function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dexpinv", [](const su& a, const su& b, const size_t order){return Lielab::functions::dexpinv(a, b, order);}, "The dexpinv function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dexpinv", [](const CompositeAlgebra& a, const CompositeAlgebra& b){return Lielab::functions::dexpinv(a, b);}, "The dexpinv function.");
    m_functions.def("dlog_numerical", [](const cn& a, const size_t order){return Lielab::functions::dlog_numerical(a, order);}, "The numerical dlog function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dlog_numerical", [](const cn& a, const cn& b, const size_t order){return Lielab::functions::dlog_numerical(a, b, order);}, "The numerical dlog function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dlog_numerical", [](const glr& a, const size_t order){return Lielab::functions::dlog_numerical(a, order);}, "The numerical dlog function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dlog_numerical", [](const glr& a, const glr& b, const size_t order){return Lielab::functions::dlog_numerical(a, b, order);}, "The numerical dlog function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dlog_numerical", [](const glc& a, const size_t order){return Lielab::functions::dlog_numerical(a, order);}, "The numerical dlog function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dlog_numerical", [](const glc& a, const glc& b, const size_t order){return Lielab::functions::dlog_numerical(a, b, order);}, "The numerical dlog function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dlog_numerical", [](const rn& a, const size_t order){return Lielab::functions::dlog_numerical(a, order);}, "The numerical dlog function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dlog_numerical", [](const rn& a, const rn& b, const size_t order){return Lielab::functions::dlog_numerical(a, b, order);}, "The numerical dlog function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dlog_numerical", [](const se& a, const size_t order){return Lielab::functions::dlog_numerical(a, order);}, "The numerical dlog function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dlog_numerical", [](const se& a, const se& b, const size_t order){return Lielab::functions::dlog_numerical(a, b, order);}, "The numerical dlog function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dlog_numerical", [](const so& a, const size_t order){return Lielab::functions::dlog_numerical(a, order);}, "The numerical dlog function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dlog_numerical", [](const so& a, const so& b, const size_t order){return Lielab::functions::dlog_numerical(a, b, order);}, "The numerical dlog function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dlog_numerical", [](const sp& a, const size_t order){return Lielab::functions::dlog_numerical(a, order);}, "The numerical dlog function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dlog_numerical", [](const sp& a, const sp& b, const size_t order){return Lielab::functions::dlog_numerical(a, b, order);}, "The numerical dlog function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dlog_numerical", [](const su& a, const size_t order){return Lielab::functions::dlog_numerical(a, order);}, "The numerical dlog function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dlog_numerical", [](const su& a, const su& b, const size_t order){return Lielab::functions::dlog_numerical(a, b, order);}, "The numerical dlog function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dlog", [](const cn& a, const size_t order){return Lielab::functions::dlog(a, order);}, "The dlog function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dlog", [](const cn& a, const cn& b, const size_t order){return Lielab::functions::dlog(a, b, order);}, "The dlog function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dlog", [](const glr& a, const size_t order){return Lielab::functions::dlog(a, order);}, "The dlog function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dlog", [](const glr& a, const glr& b, const size_t order){return Lielab::functions::dlog(a, b, order);}, "The dlog function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dlog", [](const glc& a, const size_t order){return Lielab::functions::dlog(a, order);}, "The dlog function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dlog", [](const glc& a, const glc& b, const size_t order){return Lielab::functions::dlog(a, b, order);}, "The dlog function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dlog", [](const rn& a, const size_t order){return Lielab::functions::dlog(a, order);}, "The dlog function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dlog", [](const rn& a, const rn& b, const size_t order){return Lielab::functions::dlog(a, b, order);}, "The dlog function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dlog", [](const se& a, const size_t order){return Lielab::functions::dlog(a, order);}, "The dlog function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dlog", [](const se& a, const se& b, const size_t order){return Lielab::functions::dlog(a, b, order);}, "The dlog function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dlog", [](const so& a, const size_t order){return Lielab::functions::dlog(a, order);}, "The dlog function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dlog", [](const so& a, const so& b, const size_t order){return Lielab::functions::dlog(a, b, order);}, "The dlog function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dlog", [](const sp& a, const size_t order){return Lielab::functions::dlog(a, order);}, "The dlog function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dlog", [](const sp& a, const sp& b, const size_t order){return Lielab::functions::dlog(a, b, order);}, "The dlog function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("dlog", [](const su& a, const size_t order){return Lielab::functions::dlog(a, order);}, "The dlog function.", py::arg("a"), py::arg("order") = 5);
    m_functions.def("dlog", [](const su& a, const su& b, const size_t order){return Lielab::functions::dlog(a, b, order);}, "The dlog function.", py::arg("a"), py::arg("b"), py::arg("order") = 5);
    m_functions.def("pair", &Lielab::functions::pair<cn>, "The pair function.");
    m_functions.def("pair", &Lielab::functions::pair<glr>, "The pair function.");
    m_functions.def("pair", &Lielab::functions::pair<glc>, "The pair function.");
    m_functions.def("pair", &Lielab::functions::pair<rn>, "The pair function.");
    m_functions.def("pair", &Lielab::functions::pair<se>, "The pair function.");
    m_functions.def("pair", &Lielab::functions::pair<so>, "The pair function.");
    m_functions.def("pair", &Lielab::functions::pair<sp>, "The pair function.");
    m_functions.def("pair", &Lielab::functions::pair<su>, "The pair function.");
}
