name: test-cpp

on: 
 - push
 - pull_request

jobs:
  test-linux-x86-64:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux_2_28_x86_64
      options: --cpus 1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Ensure pip is installed
        run: python3 -m ensurepip --upgrade
      - name: Get Conan for dependencies
        run: pip3 install conan
      - name: Detect Conan profile
        run: conan profile detect --force
      - name: Build the tests
        run: conan build . --version=0.5.2 -s:a build_type=Debug -s:a compiler.cppstd=gnu20 -o:a "&:with_tests=True" --build=missing
      - name: Run C++ tests
        working-directory: ./build/Debug/tests
        run: ./test_Lielab
  
  cppcheck-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Ensure cmake and cppcheck are installed
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake cppcheck
      - name: Ensure pip is installed
        run: sudo apt install -y python3-pip
      - name: Get Conan for dependencies
        run: pip3 install conan --break-system-packages
      - name: Detect Conan profile
        run: conan profile detect --force
      - name: Install deps
        run: conan install . --version=0.5.2 -s:a build_type=Debug -s:a compiler.cppstd=gnu20 --build=missing
      - name: CMake configure, returning info for cppcheck
        run: cmake --preset conan-debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - name: Run cppcheck
        run: cppcheck --enable=all --project=./build/Debug/compile_commands.json --output-file=cppcheck_results.txt
      - name: Archive scan
        uses: actions/upload-artifact@v4
        with:
          name: cppcheck_scan
          path: cppcheck_results.txt